### PR TITLE
Feat/add 1.25 compatibility

### PR DESCRIPTION
**Pull request by stefanoghinelli**
Hi all, below is a summary of the changes made on the module:

- updated docs (readme, comp matrix, release notes)
- updated drone file with new deprecation checker
- updated Trivy cronjob with new apiversion

### CODE REVIEW

**Review by nutellinoit — COMMENTED** [review]
Hi @stefanoghinelli , did you test the CI with a tag v3.0.2-rc0 ?

**Comment by ralgozino** [comment]
I've pushed some changes to use vSphere instead of AWS for the e2e tests. But the tests themselves need some work.
For example, the tests are using `examples/full-harbor-with-trivy/kustomization.yaml` that has been deleted.

**Comment by stefanoghinelli** [comment]
CI tested with tag v3.0.2-rc4

**Review by ralgozino — APPROVED** [review]
LGTM

**Review by nutellinoit — APPROVED** [review]
LGTM!

**Comment by giusepperotella** [comment]
Hi @nutellinoit, We have reviewed the documentation and everything appears to be up to date.

**Pull request merged**
