### PR TITLE
[WIP] Harbor HA setup

### PR DESCRIPTION
**Pull request by lzecca78**
Hi everyone! 
I've started to craft the Harbor in HA relying on https://github.com/sighupio/fury-kubernetes-redis and https://github.com/sighupio/fury-kubernetes-postgresql in order to achieve the needed redundancy for stateful services.
I still need to test the whole setup that will be composed by the following:
1. 3 cluster nodes of PostgreSQL (coming from the fury-kubernetes-postgresql module)
2. 3 cluster nodes + 3 sentinel for Redis (coming from the fury-kubernetes-redis module)
3. setup of Harbor HA that will use the above services and will deploy all the stateless service (portal.replicas, core.replicas, jobservice.replicas, registry.replicas, chartmuseum.replicas, clair.replicas, notary.server.replicas and notary.signer.replicas) in replica > 2

I think I will start the next week to do this kind of tests, but in the meanwhile, I would like to open this PR in order to have a review for this setup that pretty much will be the final one, except for some changes that will be needed during the test

### CODE REVIEW

**Review by lnovara — COMMENTED** [review]
What about the storage for the `chartmuseum` and `registry`? I would expect an HA setup to use some kind of object storage as backend but maybe I missed the relevant bits in the config.

**Comment by lzecca78** [comment]
Currently we need to freeze this implementation because there is at least 1 of the service of Harbor (jobservice, I open an issue: https://github.com/goharbor/harbor/issues/14081 ) that doesn't support sentinel protocol so far.

**Comment by angelbarrera92** [comment]
Is it still in WIP?

**Comment by lzecca78** [comment]
This is a nice question @angelbarrera92, as you remember we've frozen this PR because of the sentinel issue missing on the jobservice. 
I dunno if the meanwhile the situation has changed or not, probably should be worth a deep dive because 9 months have passed, and probably they have fixed the underlined issue

**Comment by lzecca78** [comment]
News: was released and seems pretty evolved the `harbor-operator`: https://github.com/goharbor/harbor-operator.
Here are the specs of the manifests of the CRD: https://github.com/goharbor/harbor-operator/blob/master/docs/CRD/custom-resource-definition.md
And here are customization manifests examples on how to deploy it: https://github.com/goharbor/harbor-operator/tree/master/manifests
I think that it could be worth converting our current static implementation (that needs to handle a great number of microservices and related inheritances) to the operator pattern. This will solve even the HA problem. 
Probably is even a bigger task, but IMHO this will simply massively the current setup.
What do you think guys?

**Comment by omissis** [comment]
closing as it got outdated

**Pull request closed without merging**
